/* Simulación aislada; no carga variables de producción ni hace peticiones de red. */
import { mkdir, writeFile } from 'node:fs/promises';
import { monthlyScenario } from '../tests/helpers/monthly-scenario.mjs';

const start = performance.now();
const result = await monthlyScenario();
const output = new URL('../docs/simulacion/', import.meta.url);
await mkdir(output, { recursive: true });
const summary = { ...result.summary, durationMs: Math.round(performance.now() - start), storage: 'Google simulado en memoria; cero escrituras reales', stats: result.h.stats };
const labels = { period: 'Periodo', students: 'Alumnos inscritos', reservations: 'Reservas (incluye historial de cambios)', attendance: 'Asistencias', countedAbsences: 'Faltas contabilizadas', blocked: 'Alumnos bloqueados', attendanceRate: 'Asistencia sobre sesiones aplicables (%)', duplicatesPrevented: 'Duplicados evitados comprobados', reactivationVerified: 'Reactivación por cierre comprobada', exportScenarios: 'Exportaciones simuladas (3 cortes + cierre)', nextMonth: 'Mes siguiente', nextMonthStudents: 'Alumnos al abrir el mes siguiente' };
await writeFile(new URL('octubre-2026-datos-ficticios.json', output), JSON.stringify({ warning: 'DATOS FICTICIOS. No importar a producción.', summary, registeredInputs: result.inputs, october: result.october, nextMonth: result.november, events: result.events }, null, 2));
const report = `# Simulación mensual — octubre de 2026\n\nDatos completamente ficticios. Se ejecutó la API real del proyecto, el código real de Apps Script y las reglas reales, con Google/Drive/Sheets reemplazados por memoria. Ningún alumno se añadió a producción.\n\n| Indicador | Resultado |\n|---|---:|\n${Object.entries(result.summary).map(([k, v]) => `| ${labels[k] || k} | ${typeof v === 'boolean' ? v ? 'Sí' : 'No' : v} |`).join('\n')}\n\n## Flujos comprobados\n\nIngreso de ambas cuentas; rechazo de contraseña; acceso sin sesión; configuración; 120 inscripciones; duplicado; aforo 20; códigos inválidos; asistencia manual y carnet; idempotencia; horarios; cierres totales y de turno; bloqueo; cierre retroactivo y reactivación; reapertura; cambio futuro de horario; tres cortes; revocación de sesión por cambio de contraseña; cierre mensual; archivo definitivo; noviembre vacío; reintento mensual; logout.\n\n## Ejemplos ficticios\n\n${result.inputs.slice(0, 8).map(s => `- ${s.code}: ${s.names} ${s.surnames}, ciclo ${s.cycle}; ${s.slots.map(r => `${result.h.context.GymDomain.DAYS[r.day]} ${r.start}`).join(', ')}.`).join('\n')}\n\n## Límites de la prueba\n\nLa exportación ejecutó la construcción de tablas y tres gráficos de Code.js. El servicio de exportación y el binario XLSX son simulados: no se ha validado un Excel real ni la persistencia remota, cámara física, permisos de Drive o activadores reales. Las dos solicitudes al último cupo se verifican secuencialmente bajo el lock simulado; no acreditan concurrencia real de Google.\n\nTiempo local: ${summary.durationMs} ms. No equivale al tiempo en Vercel. Datos y cronología: [octubre-2026-datos-ficticios.json](octubre-2026-datos-ficticios.json).\n`;
await writeFile(new URL('RESULTADO-MENSUAL.md', output), report);
console.log(JSON.stringify(summary, null, 2));
